export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const ADD_USER = 'ADD_USER'

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
